### ISSUE TITLE
TypeError: jsdom.env is not a function

### ISSUE THREAD

**Issue by konsumer** [work-in-progress/node-itunes-epf-feedcheck#1]
I get the this error:
```
TypeError: jsdom.env is not a function
    at FileCheck._9c3‍.r.module.exports.FileCheck.check (/Users/konsumer/Desktop/adobehistorical/node_modules/itunes-epf-feedcheck/lib/file_check.js:46:20)
    at Object._9c3‍.r.module.exports.check (/Users/konsumer/Desktop/adobehistorical/node_modules/itunes-epf-feedcheck/lib/index.js:10:16)
    at Object.<anonymous> (/Users/konsumer/Desktop/adobehistorical/src/index.js:2:5)
    at Object.<anonymous> (/Users/konsumer/Desktop/adobehistorical/src/index.js)
```

with this code:

```
import epfCb from 'itunes-epf-feedcheck'
import { promisify } from 'util'
const epf = promisify(epfCb.check)

epf(process.env.EPF_USERNAME, process.env.EPF_PASSWORD)
  .then(data => {
    console.log(data)
  })
  .catch(console.error)

```

I get the same error with plain commonjs ES5 usage:

```
var epf = require('itunes-epf-feedcheck')
epf.check(process.env.EPF_USERNAME, process.env.EPF_PASSWORD, function (err, data) {
  if (err) {
    return console.error(err)
  } else {
    return console.log(JSON.stringify(data))
  }
})
```

My environment variables are set correctly.

**Comment by Behinder** [comment]
Same problem here. IS this developer alive anymore?
