### ISSUE TITLE
Stopped working after nodejs latest update :/

### ISSUE THREAD

**Issue by Behinder** [work-in-progress/node-itunes-epf-feedcheck#3]
/home/sebastian/appromocje/node_modules/itunes-epf-feedcheck/lib/file_check.js:39
      filename = _.first(items).fileName;
                               ^

TypeError: Cannot read property 'fileName' of undefined
    at FileCheck.module.exports.FileCheck.parseJsDom (/home/sebastian/appromocje/node_modules/itunes-epf-feedcheck/lib/file_check.js:39:32)
    at FileCheck.parseJsDom (/home/sebastian/appromocje/node_modules/itunes-epf-feedcheck/lib/file_check.js:3:63)
    at FileCheck.<anonymous> (/home/sebastian/appromocje/node_modules/itunes-epf-feedcheck/lib/file_check.js:50:30)
    at Object.done (/home/sebastian/appromocje/node_modules/itunes-epf-feedcheck/lib/file_check.js:3:63)
    at process.nextTick (/home/sebastian/appromocje/node_modules/jsdom/lib/old-api.js:358:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Behinder** [comment]
Update...it work displaying json in terminal but cannot save string to file
